package com.unionx.wantuo.dao;

import java.util.List;
import com.unionx.wantuo.base.BaseDao;
import com.unionx.wantuo.model.Evaluate;

public interface EvaluateMapper extends BaseDao<Evaluate>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbggenerated Thu Jan 14 16:36:00 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbggenerated Thu Jan 14 16:36:00 CST 2016
     */
    int insert(Evaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbggenerated Thu Jan 14 16:36:00 CST 2016
     */
    int insertSelective(Evaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbggenerated Thu Jan 14 16:36:00 CST 2016
     */
    Evaluate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbggenerated Thu Jan 14 16:36:00 CST 2016
     */
    int updateByPrimaryKeySelective(Evaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_evaluate
     *
     * @mbggenerated Thu Jan 14 16:36:00 CST 2016
     */
    int updateByPrimaryKey(Evaluate record);
    
    /**
     * 评价管理后台分页查询
     * @param r
     * @return
     */
    List<Evaluate> adminSelect(Evaluate record);
    
    /**
     *  评价管理后台分页查询总记录数
     * @param record
     * @return
     */
    Integer adminSelectCount(Evaluate record);
    
    /**
     * 查看机构当天是否已有评价
     * @param record
     * @return
     */
    List<Evaluate> isComments(Evaluate record);
}