package com.unionx.wantuo.dao;

import org.apache.ibatis.annotations.Param;

import com.unionx.wantuo.base.BaseDao;
import com.unionx.wantuo.model.Login;

public interface LoginMapper extends BaseDao<Login>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login
     *
     * @mbggenerated Thu Jan 14 16:37:13 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login
     *
     * @mbggenerated Thu Jan 14 16:37:13 CST 2016
     */
    int insert(Login record);

    /**
     * 登入信息保存方法
     * @param record
     * @return
     */
    int insertSelective(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login
     *
     * @mbggenerated Thu Jan 14 16:37:13 CST 2016
     */
    Login selectByPrimaryKey(Integer id);

    /**
     * 修改登入信息方法
     * @param record
     * @return
     */
    int updateByPrimaryKeySelective(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login
     *
     * @mbggenerated Thu Jan 14 16:37:13 CST 2016
     */
    int updateByPrimaryKey(Login record);
    
    /**
     * 登入查询
     * @param loginAccount 登入账号
     * @param password		登入密码
     * @return
     */
    Login findToLogin(@Param("loginAccount")String loginAccount);
    
    /**
     * 注册查询
     * @param loginAccount 输入帐号
     * @return
     */
    Login findByloginAccount(@Param("loginAccount")String loginAccount,@Param("status") String status);
    
    /**
     * 后台管理根据帐号修改家长登入信息
     * @param loginAccount
     * @return
     */
    int updateByLoginAcctounts(@Param("loginAccount")String loginAccount,@Param("status") Integer status);
    
    /**
     * 根据帐号删除登入表
     * @param loginAccount
     */
    void deleteByLoginAccount(@Param("loginAccount")String loginAccount);
}