package com.unionx.wantuo.model;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.organization_accounts
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    private String organizationAccounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.login_accounts
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    private String loginAccounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.phone
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.note
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.create_date
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.status
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.status_name
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    private String statusName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.organization_accounts
     *
     * @return the value of t_order.organization_accounts
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    public String getOrganizationAccounts() {
        return organizationAccounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.organization_accounts
     *
     * @param organizationAccounts the value for t_order.organization_accounts
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    public void setOrganizationAccounts(String organizationAccounts) {
        this.organizationAccounts = organizationAccounts == null ? null : organizationAccounts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.login_accounts
     *
     * @return the value of t_order.login_accounts
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    public String getLoginAccounts() {
        return loginAccounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.login_accounts
     *
     * @param loginAccounts the value for t_order.login_accounts
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    public void setLoginAccounts(String loginAccounts) {
        this.loginAccounts = loginAccounts == null ? null : loginAccounts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.phone
     *
     * @return the value of t_order.phone
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.phone
     *
     * @param phone the value for t_order.phone
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.note
     *
     * @return the value of t_order.note
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.note
     *
     * @param note the value for t_order.note
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.create_date
     *
     * @return the value of t_order.create_date
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.create_date
     *
     * @param createDate the value for t_order.create_date
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.status
     *
     * @return the value of t_order.status
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.status
     *
     * @param status the value for t_order.status
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.status_name
     *
     * @return the value of t_order.status_name
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.status_name
     *
     * @param statusName the value for t_order.status_name
     *
     * @mbggenerated Thu Jan 14 16:38:05 CST 2016
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName == null ? null : statusName.trim();
    }
}